#!/bin/bash
cd /opt && git clone https://github.com/vishnubob/wait-for-it.git
chmod +x /opt/wait-for-it/wait-for-it.sh
/opt/wait-for-it/wait-for-it.sh powonline-db:5432 || exit 1

cd /tmp/powonline && /opt/powonline/bin/alembic upgrade head
cd /opt/powonline && /opt/powonline/bin/gunicorn powonline.wsgi -b 0.0.0.0:80
