#!/bin/bash

CONFIG_FILE=/etc/mamerwiselen/powonline/app.ini
VIRTUAL_PROTO=${VIRTUAL_PROTO:-uwsgi}

if [[ "${POWONLINE_DSN}" != "" ]]; then
    echo ">> POWONLINE_DSN overridden in environment with ${POWONLINE_DSN}"
    /set_config ${CONFIG_FILE} db.dsn ${POWONLINE_DSN}
else
    echo ">> Using default POWONLINE_DSN"
fi


if [[ "${VIRTUAL_PROTO}" == "uwsgi" ]]; then
    echo ">> Using uWSGI binary protocol"
    cd /opt/powonline && /opt/powonline/bin/uwsgi \
        --uwsgi-socket :9000 \
        --uid powonline \
        --manage-script-name \
        --wsgi-file /opt/powonline/powonline.wsgi
else
    echo ">> Using HTTP protocol"
    cd /opt/powonline && /opt/powonline/bin/uwsgi \
        --http :9000 \
        --uid powonline \
        --manage-script-name \
        --wsgi-file /opt/powonline/powonline.wsgi
fi
