"""event-relations

Revision ID: ec1494f947a9
Revises: c2d3e4f5a6b7
Create Date: 2026-04-22 19:40:58.530259

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "ec1494f947a9"
down_revision = "c2d3e4f5a6b7"
branch_labels = None
depends_on = None


def upgrade():
    # Insert intial event
    bind = op.get_bind()
    result = bind.execute(sa.text("""
            WITH inserted AS (
                INSERT INTO event (name, time_range)
                VALUES ('Default Event', tstzrange(now(), now()))
                ON CONFLICT DO NOTHING
                RETURNING id
            )
            SELECT id FROM inserted
            UNION ALL
            SELECT id FROM event WHERE name = 'Default Event'
            LIMIT 1
            """))
    event_id = result.scalar_one()
    bind.execute(
        sa.text("UPDATE team SET event_id = :event_id").bindparams(
            event_id=event_id
        )
    )
    bind.execute(
        sa.text("UPDATE station SET event_id = :event_id").bindparams(
            event_id=event_id
        )
    )
    bind.execute(
        sa.text("UPDATE route SET event_id = :event_id").bindparams(
            event_id=event_id
        )
    )
    bind.execute(
        sa.text("UPDATE questionnaire SET event_id = :event_id").bindparams(
            event_id=event_id
        )
    )
    bind.execute(
        sa.text("UPDATE auditlog SET event_id = :event_id").bindparams(
            event_id=event_id
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "auditlog", "event_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index(op.f("ix_auditlog_event_id"), table_name="auditlog")
    op.add_column(
        "message", sa.Column("event_id", sa.Integer(), nullable=False)
    )
    bind.execute(
        sa.text("UPDATE message SET event_id = :event_id").bindparams(
            event_id=event_id
        )
    )
    op.drop_constraint(op.f("message_team_fkey"), "message", type_="foreignkey")
    op.create_foreign_key(
        None,
        "message",
        "event",
        ["event_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # Create unique key on team(name, event_id)
    op.create_unique_constraint(
        "unique_team_name_per_event", "team", ["name", "event_id"]
    )
    op.create_unique_constraint(
        "unique_station_name_per_event", "station", ["name", "event_id"]
    )
    op.create_foreign_key(
        "message_sent_to_team",
        "message",
        "team",
        ["team", "event_id"],
        ["name", "event_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "questionnaire",
        "order",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "questionnaire",
        "updated",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "questionnaire", "event_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index(op.f("ix_questionnaire_event_id"), table_name="questionnaire")
    op.drop_constraint(op.f("for_station"), "questionnaire", type_="foreignkey")
    op.create_foreign_key(
        "questionnaire_hosted_at_station",
        "questionnaire",
        "station",
        ["station_name", "event_id"],
        ["name", "event_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.add_column(
        "questionnaire_score",
        sa.Column("event_id", sa.Integer(), nullable=True),
    )
    bind.execute(
        sa.text(
            "UPDATE questionnaire_score SET event_id = :event_id"
        ).bindparams(event_id=event_id)
    )
    op.alter_column(
        "questionnaire_score",
        "event_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "questionnaire_score",
        "updated",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.drop_constraint(
        op.f("questionnaire_score_team_fkey"),
        "questionnaire_score",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("questionnaire_score_questionnaire_fkey"),
        "questionnaire_score",
        type_="foreignkey",
    )
    # Questionnaires must be unique per event
    op.create_unique_constraint(
        "unique_questionnaire_name_per_event",
        "questionnaire",
        ["name", "event_id"],
    )
    op.create_foreign_key(
        "score_for_questionnaire",
        "questionnaire_score",
        "questionnaire",
        ["questionnaire", "event_id"],
        ["name", "event_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "score_awarded_to_team",
        "questionnaire_score",
        "team",
        ["team", "event_id"],
        ["name", "event_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "route", "event_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index(op.f("ix_route_event_id"), table_name="route")
    op.add_column(
        "route_station", sa.Column("event_id", sa.Integer(), nullable=True)
    )
    op.execute(
        sa.text("UPDATE route_station SET event_id = :event_id").bindparams(
            event_id=event_id
        )
    )
    op.alter_column(
        "route_station", "event_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("route_station_route_name_fkey"),
        "route_station",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("route_station_station_name_fkey"),
        "route_station",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "has_station",
        "route_station",
        "station",
        ["station_name", "event_id"],
        ["name", "event_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        "unique_route_name_per_event", "route", ["name", "event_id"]
    )
    op.create_foreign_key(
        "has_route",
        "route_station",
        "route",
        ["route_name", "event_id"],
        ["name", "event_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "station", "event_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "station",
        "order",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("500"),
    )
    op.drop_index(op.f("ix_station_event_id"), table_name="station")
    op.alter_column(
        "team", "event_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index(op.f("ix_team_event_id"), table_name="team")
    op.drop_constraint(op.f("team_route_name_fkey"), "team", type_="foreignkey")
    op.create_foreign_key(
        "team_assigned_to_route",
        "team",
        "route",
        ["route_name", "event_id"],
        ["name", "event_id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.add_column(
        "team_station_state",
        sa.Column("event_id", sa.Integer(), nullable=True),
    )
    op.execute(
        sa.text(
            "UPDATE team_station_state SET event_id = :event_id"
        ).bindparams(event_id=event_id)
    )
    op.alter_column(
        "team_station_state",
        "event_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "team_station_state",
        "updated",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(
        op.f("team_station_state_station_name_fkey"),
        "team_station_state",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("team_station_state_team_name_fkey"),
        "team_station_state",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "team_state_at_station",
        "team_station_state",
        "station",
        ["station_name", "event_id"],
        ["name", "event_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "team_state_of_team",
        "team_station_state",
        "team",
        ["team_name", "event_id"],
        ["name", "event_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "uploads", "event_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.execute(
        sa.text("UPDATE uploads SET event_id = :event_id").bindparams(
            event_id=event_id
        )
    )
    op.alter_column(
        "uploads", "event_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index(op.f("ix_uploads_event_id"), table_name="uploads")
    op.alter_column(
        "user", "password", existing_type=postgresql.BYTEA(), nullable=True
    )
    op.add_column(
        "user_station", sa.Column("event_id", sa.Integer(), nullable=True)
    )
    op.execute(
        sa.text("UPDATE user_station SET event_id = :event_id").bindparams(
            event_id=event_id
        )
    )
    op.alter_column(
        "user_station", "event_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        op.f("user_station_station_name_fkey"),
        "user_station",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "operator_at_station",
        "user_station",
        "station",
        ["station_name", "event_id"],
        ["name", "event_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "operator_at_station", "user_station", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("user_station_station_name_fkey"),
        "user_station",
        "station",
        ["station_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("user_station", "event_id")
    op.alter_column(
        "user", "password", existing_type=postgresql.BYTEA(), nullable=False
    )
    op.create_index(
        op.f("ix_uploads_event_id"), "uploads", ["event_id"], unique=False
    )
    op.alter_column(
        "uploads", "event_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        "team_state_of_team", "team_station_state", type_="foreignkey"
    )
    op.drop_constraint(
        "team_state_at_station", "team_station_state", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("team_station_state_team_name_fkey"),
        "team_station_state",
        "team",
        ["team_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("team_station_state_station_name_fkey"),
        "team_station_state",
        "station",
        ["station_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "team_station_state",
        "updated",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("team_station_state", "event_id")
    op.drop_constraint("team_assigned_to_route", "team", type_="foreignkey")
    op.create_foreign_key(
        op.f("team_route_name_fkey"),
        "team",
        "route",
        ["route_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_team_event_id"), "team", ["event_id"], unique=False
    )
    op.alter_column(
        "team", "event_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_index(
        op.f("ix_station_event_id"), "station", ["event_id"], unique=False
    )
    op.alter_column(
        "station",
        "order",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("500"),
    )
    op.alter_column(
        "station", "event_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint("has_route", "route_station", type_="foreignkey")
    op.drop_constraint("has_station", "route_station", type_="foreignkey")
    op.create_foreign_key(
        op.f("route_station_station_name_fkey"),
        "route_station",
        "station",
        ["station_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("route_station_route_name_fkey"),
        "route_station",
        "route",
        ["route_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("route_station", "event_id")
    op.create_index(
        op.f("ix_route_event_id"), "route", ["event_id"], unique=False
    )
    op.alter_column(
        "route", "event_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        "score_awarded_to_team", "questionnaire_score", type_="foreignkey"
    )
    op.drop_constraint(
        "score_for_questionnaire", "questionnaire_score", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("questionnaire_score_questionnaire_fkey"),
        "questionnaire_score",
        "questionnaire",
        ["questionnaire"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("questionnaire_score_team_fkey"),
        "questionnaire_score",
        "team",
        ["team"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "questionnaire_score",
        "updated",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_column("questionnaire_score", "event_id")
    op.drop_constraint(
        "questionnaire_hosted_at_station", "questionnaire", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("for_station"),
        "questionnaire",
        "station",
        ["station_name"],
        ["name"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_questionnaire_event_id"),
        "questionnaire",
        ["event_id"],
        unique=False,
    )
    op.alter_column(
        "questionnaire", "event_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "questionnaire",
        "updated",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "questionnaire",
        "order",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.drop_constraint("message_sent_to_team", "message", type_="foreignkey")
    op.create_foreign_key(
        op.f("message_team_fkey"),
        "message",
        "team",
        ["team"],
        ["name"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("message", "event_id")
    op.create_index(
        op.f("ix_auditlog_event_id"), "auditlog", ["event_id"], unique=False
    )
    op.alter_column(
        "auditlog", "event_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
    op.drop_constraint("unique_team_name_per_event", "team", type_="unique")
    op.drop_constraint(
        "unique_station_name_per_event", "station", type_="unique"
    )
    op.drop_constraint(
        "unique_questionnaire_name_per_event", "questionnaire", type_="unique"
    )
    op.drop_constraint("unique_route_name_per_event", "route", type_="unique")
