all:
	docker build \
		-t exhuma/powonline-db \
		-t registry.digitalocean.com/michel-albert/powonline-db:2023.05.05 \
		.

push:
	docker push \
		registry.digitalocean.com/michel-albert/powonline-db:2023.05.05
