---
name: Build and Publish
"on":
  workflow_dispatch:
  push: null
jobs:
  build_and_push:
    if: "${{ startsWith(github.ref, 'refs/tags/v') \
        || github.ref == 'refs/heads/develop' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add build dependencies
        run: pip install yq
      - name: Get Version
        run: echo "PROJECT_VERSION=$(tomlq -r .project.version pyproject.toml)"
          >> "${GITHUB_ENV}"
      - name: Build Image
        run: "
          docker buildx build
          -t \"${{secrets.DOCKER_REGISTRY}}/\
          ${{secrets.DOCKER_REGISTRY_NAMESPACE}}/\
          powonline-api:${PROJECT_VERSION}\"
          -t \"${{secrets.DOCKER_REGISTRY}}/\
          ${{secrets.DOCKER_REGISTRY_NAMESPACE}}/\
          powonline-api:dev\"
          ."
      - name: Login to Private Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push Docker Image (release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: "docker push \"${{secrets.DOCKER_REGISTRY}}/\
          ${{secrets.DOCKER_REGISTRY_NAMESPACE}}/\
          powonline-api:${PROJECT_VERSION}\""
      - name: Push dev-build
        if: github.ref == 'refs/heads/develop'
        run: "docker push \"${{secrets.DOCKER_REGISTRY}}/\
          ${{secrets.DOCKER_REGISTRY_NAMESPACE}}/\
          powonline-api:dev\""

  build_and_push_db:
    if: "${{ startsWith(github.ref, 'refs/tags/v') \
        || github.ref == 'refs/heads/develop' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add build dependencies
        run: pip install yq
      - name: Get Version
        run: echo "PROJECT_VERSION=$(tomlq -r .project.version pyproject.toml)"
          >> "${GITHUB_ENV}"
      - name: Build Database
        run: "
          cd database &&
          docker buildx build
          -t \"${{secrets.DOCKER_REGISTRY}}/\
          ${{secrets.DOCKER_REGISTRY_NAMESPACE}}/\
          powonline-db:${PROJECT_VERSION}\"
          -t \"${{secrets.DOCKER_REGISTRY}}/\
          ${{secrets.DOCKER_REGISTRY_NAMESPACE}}/\
          powonline-db:dev\"
          ."
      - name: Login to Private Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push Database Image (release)
        if: startsWith(github.ref, 'refs/tags/v')
        run: "docker push \"${{secrets.DOCKER_REGISTRY}}/\
          ${{secrets.DOCKER_REGISTRY_NAMESPACE}}/\
          powonline-db:${PROJECT_VERSION}\""
      - name: Push database dev-build
        if: github.ref == 'refs/heads/develop'
        run: "docker push \"${{secrets.DOCKER_REGISTRY}}/\
          ${{secrets.DOCKER_REGISTRY_NAMESPACE}}/\
          powonline-db:dev\""
